# Generated by Django 4.0 on 2022-08-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=True, verbose_name='Publicado/No Publicado'),
        ),
    ]
