# Generated by Django 4.0 on 2022-08-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_fecha_publicacion_alter_post_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_referencial2',
            field=models.URLField(blank=True, verbose_name='Imagen'),
        ),
    ]
