# Generated by Django 4.0 on 2022-08-23 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_imagen_referencial2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen_referencial2',
        ),
    ]
