# Generated by Django 4.0 on 2022-08-25 04:56

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('posts', '0004_remove_post_imagen_referencial2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_referencial',
            field=models.ImageField(upload_to=posts.models.post_directory_path_image, verbose_name='Imagen Referencial'),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_comentario', to='auth.user')),
            ],
        ),
    ]
