# Generated by Django 4.0 on 2022-08-26 02:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comentarios_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=ckeditor.fields.RichTextField(verbose_name='Comentario'),
        ),
    ]
