# Generated by Django 4.0 on 2022-08-22 01:10

import cuentas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_perfil_options_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='imagenes/perfilsinfoto.png', upload_to=cuentas.models.user_directory_path_profile, verbose_name='Foto'),
        ),
    ]
