# Generated by Django 4.0 on 2022-08-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.TextField(blank=True, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.TextField(blank=True, null=True, verbose_name='Nombre'),
        ),
    ]
