# Generated by Django 4.0 on 2022-08-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_perfil_apellido_alter_perfil_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
